#
version: "3.4"

x-service: &service
  build: .
  restart: always
  networks:
    - app
  depends_on:
    - redis

x-invsvc: &invsvc
  <<: *service
  command: "/app/invsvc"

x-impsvc: &impsvc
  <<: *service
  command: "/app/impsvc"


x-common-env: &common-env
  ECOM_HOST: "http://ws.erkapharm.com:8990/ecom/hs/"
  REDIS_HOST: "redis:6379"
  DB_HOST: "db-shop-01.dev.erkapharm.ru"
  IMPORT_INTERVAL_MINUTES: 720

x-conf-superapteka: &conf-superapteka
  <<: *common-env
  ECOM_USER: "SuperApteka"
  ECOM_PASSWORD: "A66VID"
  INVENTORY_DB: "2"
  SHOP_FLUSHURL: "https://rc.superapteka.ru/api/stores/on-stocks-changed"
  DB_DATABASE: "ultrashop_superapteka"
  DB_USERNAME: "ultrashop_superapteka"
  DB_PASSWORD: "DELJrYD8ieST"

x-conf-oz: &conf-oz
  <<: *common-env
  ECOM_USER: "SiteOz"
  ECOM_PASSWORD: "AV74D8"
  INVENTORY_DB: "4"
  SHOP_FLUSHURL: "https://rc.ozerki.ru/api/stores/on-stocks-changed"
  DB_DATABASE: "ultrashop_ozerki"
  DB_USERNAME: "ultrashop_ozerki"
  DB_PASSWORD: "Fiz8SMFfPx0U"

x-conf-sf: &conf-sf
  <<: *common-env
  ECOM_USER: "Samson"
  ECOM_PASSWORD: "VP9TM4"
  INVENTORY_DB: "5"
  SHOP_FLUSHURL: "https://rc-dev.samson-pharma.ru/api/stores/on-stocks-changed"
  DB_DATABASE: "ultrashop_samson"
  DB_USERNAME: "ultrashop_samson"
  DB_PASSWORD: "5M1nFfA2StRb"


x-conf-st: &conf-st
  <<: *common-env
  ECOM_USER: "StoletovSite"
  ECOM_PASSWORD: "VKR435"
  INVENTORY_DB: "6"
  SHOP_FLUSHURL: "https://rc.stoletov.ru/api/stores/on-stocks-changed"
  DB_DATABASE: "ultrashop_stoletov"
  DB_USERNAME: "ultrashop_stoletov"
  DB_PASSWORD: "2A9SPP5W2jJh"

services:
  invsvc_superapteka:
    <<: *invsvc
    environment:
      <<: *conf-superapteka
    ports:
      - "8042:8000"
  invsvc_oz:
    <<: *invsvc
    environment:
      <<: *conf-oz
    ports:
      - "8044:8000"
  invsvc_sf:
    <<: *invsvc
    environment:
      <<: *conf-sf
    ports:
      - "8045:8000"
  invsvc_st:
    <<: *invsvc
    environment:
      <<: *conf-st
    ports:
      - "8046:8000"
  impsvc_superapteka:
    <<: *impsvc
    environment:
      <<: *conf-superapteka
  impsvc_oz:
    <<: *impsvc
    environment:
      <<: *conf-oz
  impsvc_sf:
    <<: *impsvc
    environment:
      <<: *conf-sf
  impsvc_st:
    <<: *impsvc
    environment:
      <<: *conf-st
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  redis:
    driver: local
